######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 4 11:47:32 2011
######################################################################

#TEMPLATE = app
#TARGET =
#DEPENDPATH += .
#INCLUDEPATH += .

# Input
HEADERS += llkgame.h mainwindow.h
SOURCES += llkgame.cpp main.cpp mainwindow.cpp
RESOURCES += res.qrc
QT += widgets

#greaterThan(QT_MAJOR_VERSION, 5): QT += core5compat

